spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myLogTrace?serverTimezone=Asia/Seoul
    username: system
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
    use_sql_comments: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  logging:
    level:
      org.hibernate.SQL: debug
decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j
      multiline: true